### ISSUE TITLE
vectorize.not_entitled [code: 1005] - Billing Issue and Contribution Blocker

### ISSUE THREAD

**Issue by NikhilKalloli** [RafalWilinski/cloudflare-rag#8]
I'm encountering an issue where my card is being declined on Cloudflare, which is preventing me from gaining access to the [Vectorize](https://developers.cloudflare.com/vectorize/)and [R2](https://developers.cloudflare.com/r2/) features. Specifically, I receive the following error when trying to create a Vectorize index:
` vectorize.not_entitled [code: 1005]`

I'm really interested in contributing to this project, but without access to these services, it becomes challenging to follow through with the intended use of Cloudflare's tools.

Request:

1. Could you provide any guidance on how I can resolve this billing issue?
2. Are there any alternative methods for contribution that wouldn't bypass Cloudflare's services, but would allow me to keep progressing?  

Additional Info: I've considered using alternative services to replace Vectorize and R2, but that would detract from the goal of working with Cloudflare.

Any advice or suggestions would be much appreciated.

**Comment by RafalWilinski** [comment]
Hi, Vectorize is only acessible to customers on Workers Paid plan: https://developers.cloudflare.com/vectorize/get-started/intro/

**Comment by NikhilKalloli** [comment]
Thanks for the clarification!!
